- project:
    check:
      jobs:
        - f34-gcc-cover:
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/sysrepo/sysrepo
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/2021-10-08
              - name: github/rollbear/trompeloeil
                override-checkout: v41
              - name: CzechLight/libyang-cpp
              - name: CzechLight/sysrepo-cpp
            pre-run: ci/pre.yaml
        - f34-clang-asan-ubsan:
            requires: CzechLight-deps-f34-clang-asan-ubsan
            required-projects: *projects
            pre-run: ci/pre.yaml
        - f34-clang-tsan:
            requires: CzechLight-deps-f34-clang-tsan
            required-projects: *projects
            pre-run: ci/pre.yaml
        - f34-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f34-gcc-cover-previous:
            requires: CzechLight-deps-f34-gcc
            required-projects: *projects
            pre-run: ci/pre.yaml
