- job:
    name: sysrepo-ietf-alarms-f34-clang-asan-ubsan
    parent: f34-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-clang-asan-ubsan
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/sysrepo-ietf-alarms'].src_dir }}"

- project:
    check:
      jobs:
        - f34-gcc-cover:
            pre-run: ci/pre.yaml
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/sysrepo/sysrepo
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/2021-10-08
              - name: github/rollbear/trompeloeil
                override-checkout: v42
              - name: CzechLight/libyang-cpp
              - name: CzechLight/sysrepo-cpp
        - sysrepo-ietf-alarms-f34-clang-asan-ubsan:
            pre-run: ci/pre.yaml
            required-projects: *projects
        - f34-clang-tsan:
            pre-run: ci/pre.yaml
            required-projects: *projects
        - f34-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f34-gcc-cover-previous:
            pre-run: ci/pre.yaml
            required-projects: *projects
