- job:
    name: sysrepo-ietf-alarms-f34-clang-asan-ubsan
    parent: f34-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-clang-asan-ubsan
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/sysrepo-ietf-alarms'].src_dir }}"

- project:
    check:
      jobs:
        - f34-gcc-cover:
            requires: CzechLight-deps-f34-gcc
            required-projects: &projects
              - CzechLight/dependencies
            pre-run: ci/pre.yaml
        - sysrepo-ietf-alarms-f34-clang-asan-ubsan:
            required-projects: *projects
        - f34-clang-tsan:
            requires: CzechLight-deps-f34-clang-tsan
            required-projects: *projects
            pre-run: ci/pre.yaml
        - f34-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f34-gcc-cover-previous:
            requires: CzechLight-deps-f34-gcc
            required-projects: *projects
            pre-run: ci/pre.yaml
